port = 0

dhcp-range=192.168.178.1,proxy

# U-Boot
dhcp-pxe-vendor=PXEClient,U-Boot.armv8
dhcp-match=set:uboot_aarch64,option:client-arch,22
pxe-service=tag:uboot_aarch64,ARM64_EFI,"Network Boot",
dhcp-boot=tag:uboot_aarch64,ipxe.efi

# iPXE
dhcp-userclass=set:ipxe,iPXE
dhcp-boot=tag:ipxe,http://192.168.178.20:8080/boot.ipxe

enable-tftp
tftp-root=/run/media/data/moritz/Repositories/moritz/autopilot1422/tftpboot

log-dhcp
log-queries
